name = "examprep"
compatibility_date = "2023-10-30"
send_metrics = false
node_compat = true
route = "examprep.kelvin-pompey.workers.dev"
workers_dev = false
compatibility_flags = [ "nodejs_compat" ]

[env.preview]
name = "examprep-dev.kelvin-pompey.workers.dev"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
